name: Flutter CI

on:
  push:
    branches: [development, main, production]
  pull_request:
    branches: [development, main, production]

jobs:
  build:
    name: build (Flutter CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v2
        with:
          version: "3.29.3"
          channel: "stable"

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install dependencies
        run: flutter pub get

      - name: Check code format
        run: dart format . --output=none --set-exit-if-changed

      - name: Static analysis
        run: flutter analyze

      - name: Dry run fixes
        run: dart fix --dry-run

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Upload coverage to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov.info
