name: Semantic Release

on:
  workflow_run:
    workflows: ["Flutter CI"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install -g \
            conventional-changelog-cli \
            conventional-recommended-bump \
            conventional-changelog-angular

      - name: Compute next version and generate changelog
        id: versioning
        run: |
          CURRENT_VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          echo "Current version: $CURRENT_VERSION"

          # Get recommended bump (major, minor, patch)
          BUMP_TYPE=$(npx conventional-recommended-bump -p angular | grep '"releaseType"' | cut -d '"' -f4)
          echo "Recommended bump: $BUMP_TYPE"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          if [ "$BUMP_TYPE" = "major" ]; then
            MAJOR=$((MAJOR + 1)); MINOR=0; PATCH=0
          elif [ "$BUMP_TYPE" = "minor" ]; then
            MINOR=$((MINOR + 1)); PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi

          NEXT_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "Next version: $NEXT_VERSION"

          echo "next_version=$NEXT_VERSION" >> $GITHUB_OUTPUT

          # Update version in pubspec.yaml
          sed -i "s/^version: .*/version: $NEXT_VERSION/" pubspec.yaml

          # Update iOS version in project.pbxproj
          PBXPROJ_FILE="ios/Runner.xcodeproj/project.pbxproj"
          sed -i "s/MARKETING_VERSION = .*/MARKETING_VERSION = $NEXT_VERSION;/g" "$PBXPROJ_FILE"

          # Generate or update changelog
          npx conventional-changelog -p angular -i CHANGELOG.md -s

          # Commit & tag (DEPRECATED)
          # git config user.name "github-actions[bot]"
          # git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # git add pubspec.yaml ios/Runner.xcodeproj/project.pbxproj CHANGELOG.md
          # git commit -m "chore(release): v$NEXT_VERSION [skip ci]" || echo "No changes to commit"
          # git tag "v$NEXT_VERSION"
          # git push origin HEAD:main --tags

      - name: Commit updated files
        run: |
          git checkout -b release/v${{ steps.versioning.outputs.next_version }}
          git add pubspec.yaml ios/Runner.xcodeproj/project.pbxproj CHANGELOG.md
          git commit -m "chore(release): v${{ steps.versioning.outputs.next_version }} [skip ci]"

      - name: Push release branch
        run: |
          git push origin release/v${{ steps.versioning.outputs.next_version }} --set-upstream

      - name: Open Pull Request to main
        uses: peter-evans/create-pull-request@v6
        with:
          branch: release/v${{ steps.versioning.outputs.next_version }}
          title: "chore(release): v${{ steps.versioning.outputs.next_version }}"
          body: "This PR prepares version `${{ steps.versioning.outputs.next_version }}` with changelog and version bump."
          base: main
          delete-branch: false
