name: Tag and Release

on:
  pull_request:
    branches: [production]
    types: [closed]

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout production
        uses: actions/checkout@v4
        with:
          ref: production
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Extract version and create tag
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          echo "Tagging version: $VERSION"
          git tag "v$VERSION"
          git push origin "v$VERSION"
